# -*- coding: utf-8 -*-
"""01_Data_Division.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x96h7OI2wGuJo69OPVGpdws6N56dz27R

# **Mount The Drive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""# **Install & Import Dependencies**"""

!pip -q install shapely pyogrio rtree

import geemap
import ee
import geopandas as gpd
import pandas as pd
import numpy as np
import seaborn as sns
import random
from shapely.geometry import Point
from pyproj import CRS
from shapely.prepared import prep
import os

"""# **Load The Data**"""

Point_data = ee.FeatureCollection('projects/ee-ranitsundarchatterjee/assets/Crop_Classification/Data_Points')
Polygon_data = ee.FeatureCollection('projects/ee-ranitsundarchatterjee/assets/Crop_Classification/Data_polygons')
updated_points = gpd.read_file('/content/drive/MyDrive/Crop_Classification/Data/Shapefiles/Updated_Points/Extra_Added_Points.shp')

"""## **Check Required values**"""

# Check Values in 'Season' Column
season_values = updated_points['season'].unique()
season_values

"""## **Download As Required**"""

# Download the divided dataset as per the 'Season' Column
output_dir = '/content/drive/MyDrive/Crop_Classification/Data/Shapefiles/Season_Shapefiles'
if not os.path.exists(output_dir):
  os.makedirs(output_dir)

for i in updated_points['season'].unique():
  gdf_data = updated_points[updated_points['season'] == i]
  # Save to GeoJSON to avoid shapefile column name limitations
  output_save = os.path.join(output_dir, f'{i}_Season.geojson')
  gdf_data.to_file(output_save, driver='GeoJSON')

"""# **Load all the Season Data**"""

kharif = gpd.read_file('/content/drive/MyDrive/Crop_Classification/Data/Shapefiles/Season_Shapefiles/kharif_Season.geojson')
rabi = gpd.read_file('/content/drive/MyDrive/Crop_Classification/Data/Shapefiles/Season_Shapefiles/rabi_Season.geojson')
perennial = gpd.read_file('/content/drive/MyDrive/Crop_Classification/Data/Shapefiles/Season_Shapefiles/perennial_Season.geojson')
zaid = gpd.read_file('/content/drive/MyDrive/Crop_Classification/Data/Shapefiles/Season_Shapefiles/zaid_Season.geojson')

"""## **Check The Unique Values of a Single file**"""

perennial['Label'].unique()

"""# **In This Case:**

Values in Zaid season is: ['aus_rice' 'maize' 'groundnut']<br>
Values in Rabi season is: ['maize' 'tobacco' 'boro_rice' 'vegetables' 'mustard' 'flower' 'potato'
 'others' 'wheat']<br>
 Values in Kharif season is: ['aman_rice' 'jute']<br>
 Values in Perennial season is: ['banana', 'betel_leaf', 'pine_apple', 'sugarcane', 'tea']

## **Concating Each of the dataset & Prepare the final data**
"""

all_Perennial = pd.concat([kharif, rabi, zaid, perennial], ignore_index=True)
all_Perennial

"""## **Marking Other values**"""

all_Perennial.loc[~all_Perennial['Label'].isin(['banana', 'betel_leaf', 'pine_apple', 'sugarcane', 'tea']), 'Label'] = 'Others'
print(all_Perennial['Label'].unique())

"""## **Download the data**"""

# all_Perennial.to_file('/content/drive/MyDrive/Crop_Classification/Data/Shapefiles/Season_Shapefiles/Perennial_Season/Perennial.shp', driver='ESRI Shapefile')