# -*- coding: utf-8 -*-
"""02_Data_Download.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_wqo80b7TBEsaYdnKgX4u8uejNBqhWP8

# **Mount The Drive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""# **Install & Import Dependencies**"""

!pip install geopandas shapely pystac-client planetary-computer requests tqdm

import os
import requests
import geopandas as gpd
import planetary_computer
from pystac_client import Client
from tqdm import tqdm

"""# **Prepare the Area of Interest**"""

# 1. Load the GPKG file and extract the geometry
wb_gdf = gpd.read_file("/content/drive/MyDrive/Crop_Classification/Data/west_bengal.gpkg")

# STAC APIs always expect coordinates in WGS84 (EPSG:4326).
# This safely reprojects your data if it is in another format (like UTM).
gdf = wb_gdf.to_crs("EPSG:4326")

# Combine all polygons in the GPKG into one single boundary shape
# Shapely geometries natively support the __geo_interface__ property required by pystac-client
wb_geometry = gdf.union_all()

"""# **Algorithm For Satellite Data Download**

## **Sentinel-1**
"""

# 2. Connect to the Microsoft Planetary Computer STAC API
catalog = Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
    modifier=planetary_computer.sign_inplace,
)

# 3. Define your search parameters
date_range = "2015-01-01/2024-12-31"

print("Searching for Sentinel-1 scenes intersecting the GPKG boundary...")
search = catalog.search(
    collections=["sentinel-1-rtc"],
    bbox=list(wb_geometry.bounds),      # <--- Using bounding box (bbox parameter) instead of intersects
    datetime=date_range,
)

# Fetch all matched items
items = list(search.items())
print(f"Total scenes found: {len(items)}")

# 4. Download the data
download_dir = "/content/drive/MyDrive/Crop_Classification/Satellite_Data/S_1"
os.makedirs(download_dir, exist_ok=True)

# WARNING: Limited to the first 2 images for demonstration.
# Remove the [:2] slice to process the entire archive.
for item in items[:2]:
    print(f"\nProcessing Scene: {item.id}")
    print(f"Acquisition Date: {item.datetime}")

    polarizations_to_download = ["vv", "vh"]

    for pol in polarizations_to_download:
        if pol in item.assets:
            asset = item.assets[pol]
            file_url = asset.href
            file_name = os.path.join(download_dir, f"{item.id}_{pol}.tif")

            # Stream download for large files with tqdm progress bar
            with requests.get(file_url, stream=True) as r:
                r.raise_for_status()

                # Get the total file size from headers (in bytes)
                total_size = int(r.headers.get('content-length', 0))

                # Initialize tqdm progress bar
                with open(file_name, "wb") as f, tqdm(
                    desc=f"Downloading {pol.upper()}",
                    total=total_size,
                    unit="B",
                    unit_scale=True,
                    unit_divisor=1024,
                ) as bar:
                    for chunk in r.iter_content(chunk_size=8192):
                        if chunk:  # filter out keep-alive new chunks
                            f.write(chunk)
                            bar.update(len(chunk)) # Update the progress bar

            print(f"Saved to: {file_name}")
        else:
            print(f"Polarization {pol.upper()} not found for this scene.")

print("\nDownload process completed.")

"""## **Sentinel-2**"""

# 2. Connect to the Microsoft Planetary Computer STAC API
catalog = Client.open(
    "https://planetarycomputer.microsoft.com/api/stac/v1",
    modifier=planetary_computer.sign_inplace,
)

# 3. Define search parameters
date_range = "2016-01-01/2024-12-31"

print("Searching for cloud-free Sentinel-2 scenes intersecting the GPKG boundary...")
search = catalog.search(
    collections=["sentinel-2-l2a"],
    bbox=list(wb_geometry.bounds),
    datetime=date_range,
    # Crucial for optical data: filter out cloudy scenes
    query={"eo:cloud_cover": {"lt": 10}}  # Less than 10% cloud cover
)

items = list(search.items())
print(f"Total cloud-free scenes found: {len(items)}")

# 4. Download the data
download_dir = "/content/drive/MyDrive/Crop_Classification/Satellite_Data/S_2"
os.makedirs(download_dir, exist_ok=True)

# WARNING: Limited to the first 2 images for demonstration.
# Remove the [:2] slice to process the entire filtered archive.
for item in items[:2]:
    print(f"\nProcessing Scene: {item.id}")
    print(f"Acquisition Date: {item.datetime}")
    print(f"Cloud Cover: {item.properties.get('eo:cloud_cover', 'N/A')}%")

    # Select which bands/assets to download
    # B02 (Blue), B03 (Green), B04 (Red), B08 (NIR) are 10m resolution.
    # 'visual' is a pre-rendered True Color RGB image (also 10m).
    # 'SCL' is the Scene Classification Layer (useful for masking clouds/shadows).
    assets_to_download = ["B02", "B03", "B04", "B08", "visual"]

    for asset_name in assets_to_download:
        if asset_name in item.assets:
            asset = item.assets[asset_name]
            file_url = asset.href

            # Use appropriate file extension (most bands are .tif)
            ext = ".tif" if asset.media_type and "tiff" in asset.media_type else ""
            file_name = os.path.join(download_dir, f"{item.id}_{asset_name}{ext}")

            # Stream download with tqdm progress bar
            with requests.get(file_url, stream=True) as r:
                r.raise_for_status()
                total_size = int(r.headers.get('content-length', 0))

                with open(file_name, "wb") as f, tqdm(
                    desc=f"Downloading {asset_name}",
                    total=total_size,
                    unit="B",
                    unit_scale=True,
                    unit_divisor=1024,
                ) as bar:
                    for chunk in r.iter_content(chunk_size=8192):
                        if chunk:
                            f.write(chunk)
                            bar.update(len(chunk))

            print(f"Saved to: {file_name}")
        else:
            print(f"Asset {asset_name} not found for this scene.")

print("\nDownload process completed.")

